server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Order Service
        - id: order-service
          uri: http://order-service:8181
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: order-service-circuit-breaker
                fallbackUri: forward:/fallback/order-service

        # Payment Service
        - id: payment-service
          uri: http://payment-service:8182
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: payment-service-circuit-breaker
                fallbackUri: forward:/fallback/payment-service

        # Restaurant Service
        - id: restaurant-service
          uri: http://restaurant-service:8183
          predicates:
            - Path=/api/restaurants/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: restaurant-service-circuit-breaker
                fallbackUri: forward:/fallback/restaurant-service

        # Customer Service
        - id: customer-service
          uri: http://customer-service:8184
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: customer-service-circuit-breaker
                fallbackUri: forward:/fallback/customer-service

        # Health Check Routes
        - id: order-service-health
          uri: http://order-service:8181
          predicates:
            - Path=/api/health/orders
          filters:
            - RewritePath=/api/health/orders, /orders/health

        - id: payment-service-health
          uri: http://payment-service:8182
          predicates:
            - Path=/api/health/payments
          filters:
            - RewritePath=/api/health/payments, /payments/health

        - id: restaurant-service-health
          uri: http://restaurant-service:8183
          predicates:
            - Path=/api/health/restaurants
          filters:
            - RewritePath=/api/health/restaurants, /restaurants/health

        - id: customer-service-health
          uri: http://customer-service:8184
          predicates:
            - Path=/api/health/customers
          filters:
            - RewritePath=/api/health/customers, /customers/health

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
