apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-connector-config
  namespace: kafka-infrastructure
data:
  order-outbox-connector.json: |
    {
      "name": "order-outbox-connector",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "database.hostname": "postgres",
        "database.port": "5432",
        "database.user": "postgres",
        "database.password": "admin",
        "database.dbname": "postgres",
        "database.server.name": "order-service",
        "topic.prefix": "order-service",
        "database.schema.include.list": "orden",
        "table.include.list": "orden.outbox_events",
        "plugin.name": "pgoutput",
        "publication.autocreate.mode": "all_tables",
        "slot.name": "order_outbox_slot",
        "transforms": "outbox",
        "transforms.outbox.type": "io.debezium.transforms.outbox.EventRouter",
        "transforms.outbox.table.field.event.key": "aggregate_id",
        "transforms.outbox.table.field.event.payload": "event_data",
        "transforms.outbox.table.field.event.timestamp": "created_at",
        "transforms.outbox.table.field.event.type": "event_type",
        "transforms.outbox.table.field.event.id": "id",
        "transforms.outbox.route.by.field": "event_type",
        "transforms.outbox.route.topic.replacement": "order-${routedByValue}",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter.schemas.enable": "false",
        "offset.flush.interval.ms": "60000"
      }
    }
