services:
  order-service:
    image: order-service:latest
    container_name: order-service
    ports:
      - "${ORDER_SERVICE_PORT}:8181"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
      - KAFKA_CONSUMER_CONFIG_RESTAURANT_APPROVAL_CONSUMER_GROUP_ID=restaurant-approval-consumer-group
      - KAFKA_CONSUMER_CONFIG_PAYMENT_CONSUMER_GROUP_ID=payment-consumer-group
      - KAFKA_CONSUMER_CONFIG_ORDER_CONSUMER_GROUP_ID=order-consumer-group
    networks:
      - kafka-network
    depends_on:
      - customer-service
      - payment-service
      - restaurant-service

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    ports:
      - "${PAYMENT_SERVICE_PORT:-8182}:8182"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
    networks:
      - kafka-network
    depends_on:
      - customer-service

  restaurant-service:
    image: restaurant-service:latest
    container_name: restaurant-service
    ports:
      - "${RESTAURANT_SERVICE_PORT:-8183}:8183"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
      - KAFKA_CONSUMER_CONFIG_RESTAURANT_APPROVAL_CONSUMER_GROUP_ID=restaurant-approval-consumer-group
      - KAFKA_CONSUMER_CONFIG_PAYMENT_CONSUMER_GROUP_ID=payment-consumer-group
      - KAFKA_CONSUMER_CONFIG_ORDER_CONSUMER_GROUP_ID=order-consumer-group
    networks:
      - kafka-network
    depends_on:
      - customer-service

  customer-service:
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "${CUSTOMER_SERVICE_PORT:-8184}:8184"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
    networks:
      - kafka-network

  consulta-service:
    image: consulta-service:latest
    container_name: consulta-service
    ports:
      - "${CONSULTA_SERVICE_PORT:-8185}:8185"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
    networks:
      - kafka-network
    # depends_on:
    #   - order-service

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092,localhost:29092,localhost:39092}
    networks:
      - kafka-network
    depends_on:
      - order-service
      - payment-service
      - restaurant-service
      - customer-service
      - consulta-service

networks:
  kafka-network:
    external: true
    name: kafka-infrastructure_kafka-network
